version: '3.7'
services:
  db:
    image: postgres:14.5-alpine
    container_name: ddd-example-db
    ports:
      - '4005:5432'
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: askit
      POSTGRES_PASSWORD: askit
    healthcheck:
      test: ['CMD-SHELL', 'echo 1']
      interval: 5s
    networks:
      - local
networks:
  local:
    driver: bridge
