services:
  Mooc.courses.CourseRepository:
    class: '../../../../Contexts/Courses/infrastructure/PostgresCourseRepository'
    arguments: []

  Mooc.courses.CourseCreator:
    class: '../../../../Contexts/Courses/application/CourseCreator'
    arguments: ['@Mooc.courses.CourseRepository']  

  Apps.todo.controllers.StatusGetController:
    class: '../../controllers/StatusGetController'
    arguments: []

  Apps.todo.controllers.CoursesPostController:
    class: '../../controllers/CoursesPostController'
    arguments: ['@Mooc.courses.CourseCreator'] 
